# Generated by Django 3.2.3 on 2021-05-18 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadunni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thread_id', models.CharField(max_length=256, unique=True)),
                ('thread', models.TextField()),
                ('link', models.CharField(max_length=250, unique=True)),
                ('owner', models.CharField(max_length=64)),
                ('owner_photo', models.CharField(max_length=256)),
                ('title', models.CharField(default='Thread', max_length=256)),
                ('thread_thumbnail', models.CharField(max_length=250)),
                ('media_url', models.CharField(default='', max_length=250)),
                ('username', models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
