# Generated by Django 3.2.3 on 2021-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadunni', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='https://www.kindpng.com/picc/m/451-4517876_default-profile-hd-png-download.png', max_length=255),
        ),
    ]
